import {Button} from '@/components/ui/button';
import './globals.css';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import Link from 'next/link';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Takehome',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className='flex items-center justify-between p-6'>
          <h1 className='text-xl font-bold'>Teacher Hub</h1>
          <Link href='/grade'>
            <Button>Submit a Grade</Button>
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
